### ISSUE TITLE
lru: panic: interface conversion: interface {} is nil, not *lru.entry

### ISSUE THREAD

**Issue by calmh** [golang/groupcache#59]
I'm occasionally getting this panic when running `Add()`:

```
http: panic serving 127.0.0.1:37287: interface conversion: interface {} is nil, not *lru.entry
goroutine 6797289 [running]:
	net/http.(*conn).serve.func1(0xc8207ee8f0, 0x7fb61f0370e0, 0xc820020510)
		#011/usr/local/go/src/net/http/server.go:1287 +0xb5
	github.com/golang/groupcache/lru.(*Cache).removeElement(0xc820152500, 0xc82011f980)
		#011/Users/jb/src/github.com/syncthing/discosrv/Godeps/_workspace/src/github.com/golang/groupcache/lru/lru.go:108 +0x1a2
	github.com/golang/groupcache/lru.(*Cache).RemoveOldest(0xc820152500)
		#011/Users/jb/src/github.com/syncthing/discosrv/Godeps/_workspace/src/github.com/golang/groupcache/lru/lru.go:102 +0x4d
	github.com/golang/groupcache/lru.(*Cache).Add(0xc820152500, 0x8c3dc0, 0xc820aa2930, 0x9f4220, 0xc8207ff9a0)
		#011/Users/jb/src/github.com/syncthing/discosrv/Godeps/_workspace/src/github.com/golang/groupcache/lru/lru.go:69 +0x2d9
	main.(*querysrv).limit(0xc820076e60, 0xc820aa2920, 0x10, 0x10, 0x10)
		#011/Users/jb/src/github.com/syncthing/discosrv/querysrv.go:308 +0x207
	main.(*querysrv).handler(0xc820076e60, 0x7fb61f038ab8, 0xc8207ee9a0, 0xc8209a9260)
		#011/Users/jb/src/github.com/syncthing/discosrv/querysrv.go:107 +0x20d
	main.(*querysrv).(main.handler)-fm(0x7fb61f038ab8, 0xc8207ee9a0, 0xc8209a9260)
		#011/Users/jb/src/github.com/syncthing/discosrv/querysrv.go:75 +0x3e
	net/http.HandlerFunc.ServeHTTP(0xc820144920, 0x7fb61f038ab8, 0xc8207ee9a0, 0xc8209a9260)
		#011/usr/local/go/src/net/http/server.go:1422 +0x3a
	net/http.(*ServeMux).ServeHTTP(0xc820053290, 0x7fb61f038ab8, 0xc8207ee9a0, 0xc8209a9260)
		#011/usr/local/go/src/net/http/server.go:1699 +0x17d
	net/http.serverHandler.ServeHTTP(0xc8200135c0, 0x7fb61f038ab8, 0xc8207ee9a0, 0xc8209a9260)
		#011/usr/local/go/src/net/http/server.go:1862 +0x19e
	net/http.(*conn).serve(0xc8207ee8f0)
		#011/usr/local/go/src/net/http/server.go:1361 +0xbee
	created by net/http.(*Server).Serve
		#011/usr/local/go/src/net/http/server.go:1910 +0x3f6
```

The code calling this is https://github.com/syncthing/discosrv/blob/master/querysrv.go#L308. It seems to start happen when the process has been running for a while. Once it starts happening, it's regular, possibly every Add() call (I'm not sure, sorry).

**Comment by calmh** [comment]
Actually, never mind. I had incorrectly assumed lru was concurrency-safe, which it obviously isn't when I actually glance at the code. :)
